// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Reaper is an autogenerated mock type for the Reaper type
type Reaper struct {
	mock.Mock
}

type Reaper_Expecter struct {
	mock *mock.Mock
}

func (_m *Reaper) EXPECT() *Reaper_Expecter {
	return &Reaper_Expecter{mock: &_m.Mock}
}

// Reap provides a mock function with given fields: _a0, _a1, _a2
func (_m *Reaper) Reap(_a0 context.Context, _a1 string, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Reap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reaper_Reap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reap'
type Reaper_Reap_Call struct {
	*mock.Call
}

// Reap is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
func (_e *Reaper_Expecter) Reap(_a0 interface{}, _a1 interface{}, _a2 interface{}) *Reaper_Reap_Call {
	return &Reaper_Reap_Call{Call: _e.mock.On("Reap", _a0, _a1, _a2)}
}

func (_c *Reaper_Reap_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string)) *Reaper_Reap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Reaper_Reap_Call) Return(_a0 error) *Reaper_Reap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Reaper_Reap_Call) RunAndReturn(run func(context.Context, string, string) error) *Reaper_Reap_Call {
	_c.Call.Return(run)
	return _c
}

// NewReaper creates a new instance of Reaper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReaper(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reaper {
	mock := &Reaper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
