name: Build

on:
  push:
    branches:
      - main
      - go123
    paths-ignore:
      - 'assets/**'

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@go1.23
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@go1.23
    with:
      image: ghcr.io/clambin/k8s-restarter
      dockerfile: build/Dockerfile
