name: Build

on:
  push:
    branches:
      - main
      - build
    paths-ignore:
      - 'assets/**'

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@docker
    with:
      image: ghcr.io/clambin/k8s-restarter
